config/routes.rb
MyProject::Application.routes.draw do
  resources :dailyhouses

  resources :guestmessages

  resources :room_statuses

  get "dashboard/login"

  get "dashboard/logout"

  get "dashboard/index"

  resources :users

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/room_statuses_controller.rb
class RoomStatusesController < ApplicationController
  # GET /room_statuses
  # GET /room_statuses.xml
  load_and_authorize_resource

  def index
    @room_statuses = RoomStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @room_statuses }
    end
  end

  # GET /room_statuses/1
  # GET /room_statuses/1.xml
  def show
    @room_status = RoomStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @room_status }
    end
  end

  # GET /room_statuses/new
  # GET /room_statuses/new.xml
  def new
    @room_status = RoomStatus.new
    @cur_user = User.find_by_id(session[:user_id])
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @room_status }
    end
  end

  # GET /room_statuses/1/edit
  def edit
    @room_status = RoomStatus.find(params[:id])
    @cur_user = User.find_by_id(session[:user_id])
  end

  # POST /room_statuses
  # POST /room_statuses.xml
  def create
    @room_status = RoomStatus.new(params[:room_status])
    @cur_user = User.find_by_id(session[:user_id])

    respond_to do |format|
      if @room_status.save
        format.html { redirect_to(@room_status, :notice => 'Room status was successfully created.') }
        format.xml  { render :xml => @room_status, :status => :created, :location => @room_status }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @room_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /room_statuses/1
  # PUT /room_statuses/1.xml
  def update
    @room_status = RoomStatus.find(params[:id])
    @cur_user = User.find_by_id(session[:user_id])

    respond_to do |format|
      if @room_status.update_attributes(params[:room_status])
        format.html { redirect_to(@room_status, :notice => 'Room status was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @room_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /room_statuses/1
  # DELETE /room_statuses/1.xml
  def destroy
    @room_status = RoomStatus.find(params[:id])
    @room_status.destroy

    respond_to do |format|
      format.html { redirect_to(room_statuses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/room_statuses_helper.rb
module RoomStatusesHelper
end

app/views/room_statuses/_form.html.erb
<%= form_for(@room_status) do |f| %>
  <% if @room_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room_status.errors.count, "error") %> prohibited this room_status from being saved:</h2>

      <ul>
      <% @room_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @cur_user.role == "manager" %>
  <div class="field">
    <b style="color:#f4a460;"><%= f.label :"Room Number" %><br />   </b>
    <%= f.text_field :roomnum %>
  </div>
  <% end %>
  <% if @cur_user.role == "manager" %>
  <div class="field">
    <b style="color:#f4a460;"><%= f.label :"Room Name" %><br />    </b>
    <%= f.select :roomname, RoomStatus::ROOMNAME %>
  </div>
  <% end %>
  <div class="field">
    <b style="color:#f4a460;"><%= f.label :"Room Status" %><br />    </b>
    <%= f.collection_select :roomstatus, RoomStatus::STATUS, :to_s, :humanize %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/room_statuses/edit.html.erb
<h1 align="center">Editing Room Status</h1>
<p></p>
<p></p>


<%= render 'form' %>

<%= link_to 'Show', @room_status %> |
<%= link_to 'Back', room_statuses_path %>

app/views/room_statuses/index.html.erb
<h1 align="center">Listing Room</h1>

<div id="form">
  <div align="right">
    <% if can? :create, @room_statuses %>
    <%= button_to 'Create New Room', new_room_status_path %>
    <% end %>

  </div>
  <table>
  <tr align="center" style="color:#f4a460;">
    <th>Room Number</th>
    <th><dd>Room Name</dd></th>
    <th><dd>Room Status</dd></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @room_statuses.each do |room_status| %>
  <tr align="center">
    <td style="color:#ffdead;"><%= room_status.roomnum %></td>
    <td style="color:#ffdead;"><dd><%= room_status.roomname %></dd></td>
    <td style="color:#ffdead;"><dd><%= room_status.roomstatus %></dd></td>
    <td><dd><%= link_to 'View', room_status %></dd></td>
    <td><%= link_to 'Edit', edit_room_status_path(room_status) %></td>

    <% if can? :Destroy, @room_statuses %>
    <td><%= link_to 'Delete', room_status, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>
</div>

app/views/room_statuses/new.html.erb
<h1 align="center">Create New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', room_statuses_path %>

app/views/room_statuses/show.html.erb
<h1 align="center">Room Information</h1>


<p id="notice"><%= notice %></p>

<p>
  <tr></tr>
  <b style="color:#f4a460;">Room Number :</b>
  <b style="color:#ffdead;"><%= @room_status.roomnum %>   </b>
</p>

<p>
  <b style="color:#f4a460;">Room Name :</b>
  <b style="color:#ffdead;"><%= @room_status.roomname %>    </b>
</p>

<p>
  <b style="color:#f4a460;">Room status :</b>
  <b style="color:#ffdead;"><%= @room_status.roomstatus %>   </b>
</p>


<%= link_to 'Edit', edit_room_status_path(@room_status) %> |
<%= link_to 'Back', room_statuses_path %>